/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_DOUBLE_NUMBER__
#define __RUST_DOUBLE_NUMBER__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
int32_t
doubleNumber (
    int32_t n);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_DOUBLE_NUMBER__ */
