/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_DOUBLE_NUMBER__
#define __RUST_DOUBLE_NUMBER__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
int32_t
doubleNumber (
    int32_t n);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

/** <No documentation available> */
Vec_uint8_t
welcome (
    Vec_uint8_t name);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_DOUBLE_NUMBER__ */
